training: !!bool "true"
device: "cuda"
unprocessed_data: '/nas/staff/data_work/Sure/TIMIT/TIMIT/*/*/*/*.wav'
---
data:
    train_path: '/nas/staff/data_work/Sure/SpeakerVerification/train_tisv'
    train_path_unprocessed: '/nas/staff/data_work/Sure/TIMIT/TIMIT/train/*/*/*.wav'
    test_path: '/nas/staff/data_work/Sure/SpeakerVerification/test_tisv'
    test_path_unprocessed: '/nas/staff/data_work/Sure/TIMIT/TIMIT/test/*/*/*.wav'
    data_preprocessed: !!bool "true" 
    sr: 16000
    nfft: 512 #For mel spectrogram preprocess
    window: 0.025 #(s)
    hop: 0.01 #(s)
    nmels: 40 #Number of mel energies
    tisv_frame: 180 #Max number of time steps in input after preprocess
---   
model:
    hidden: 768 #Number of LSTM hidden layer units
    num_layer: 3 #Number of LSTM layers
    proj: 256 #Embedding size
    model_path: '/nas/staff/data_work/Sure/TIMIT/speech_id_checkpoint/final_epoch_950_batch_id_141.model' #Model path for testing, inference, or resuming training
---
train:
    N : 4 #Number of speakers in batch
    M : 5 #Number of utterances per speaker
    num_workers: 0 #number of workers for dataloader
    lr: 0.01 
    epochs: 950 #Max training speaker epoch 
    log_interval: 30 #Epochs before printing progress
    log_file: '/nas/staff/data_work/Sure/TIMIT/speech_id_checkpoint/Stats'
    checkpoint_interval: 120 #Save model after x speaker epochs
    checkpoint_dir: '/nas/staff/data_work/Sure/TIMIT/speech_id_checkpoint'
    restore: !!bool "false" #Resume training from previous model path
---
test:
    N : 4 #Number of speakers in batch
    M : 6 #Number of utterances per speaker
    num_workers: 8 #number of workers for data laoder
    epochs: 10 #testing speaker epochs
